### ISSUE TITLE
login flashing bug

### ISSUE THREAD

**Issue by rooberrydev** [fac20/tfb-bonf#18]
The reason this is happening is because firebase takes a second to initialise, and since you're setting the loggedIn state to false when your app loads, there's a split second where it stays false before firebase loads up and the firebase `onAuthStateChanged` listener toggles it to true.

The way around this is to set a separate bit of state to wait for firebase to correctly read and set the user state.

`  const [loading, setLoading] = React.useState(true);`

loading starts off as true, and gets toggled to false when firebase reads the user state.
```javascript
if (user) {
        setLoading(false);
        setLoggedIn(true);
      } else {
        setLoading(false);
        setLoggedIn(false);
      }
```

Note how its being toggled to false regardless of the user being logged in or not. we basically only need this state so we can show a loading spinner till our app is ready to show the correct page.

We can now render a loading component if firebase is initialising, and now we can be sure that the app sees the correct value for loggedIn (it doesnt jump from false to true)

```javascript
// returns early with a loading spinner if firebase is loading
if (loading) return <Loading />
// otherwise renders route components
  return (
    <BrowserRouter>
   // rest of App.js
```

A side effect of this fix is that the loading spinner will renders on the login page as well. 

This is helpful if the user is logged in already, as it will prevent them from ever seeing the login form when they visit "/", and directly redirect them to "/home"

but if they're logged out, they'll see a loading spinner for a second before the login form renders. I can't see a way around this though, since there's no way of telling if they're logged in or out until firebase loads and sets the login state.

**Comment by rooberrydev** [comment]
Loading doesnt exist, you can create one, there are lots of css spinners available online.

A neat way to make a spinner I learnt on my last job is to have a div with a border-radius:50%,border-right: 2 px solid green, border: 2px solid grey, then put an infinite rotate() transition on it.

there's also this website 
https://projects.lukehaas.me/css-loaders/

**Comment by rooberrydev** [comment]
also, do put your onAuthStateChanged() call in a useEffect!


```javascript
useEffect(() => {
    const unsubscribe = auth().onAuthStateChanged((user) => {
      if (user) {
        setLoading(false);
        setLoggedIn(true);
      } else {
        setLoading(false);
        setLoggedIn(false);
      }
    });
    return () => unsubscribe();
  }, []);
```

**Comment by aissshah** [comment]
done :) 👍
