### ISSUE TITLE
Consider setting current user's uid in the login state

### ISSUE THREAD

**Issue by rooberrydev** [fac20/tfb-bonf#23]
Would avoid having to call auth.currentUser.uid all the time.

You'll probably find that lots of queries will need the current user's uid (especially when creating documents that can only be accessed by the current user)

Setting this in state and passing it to page components would be handy.

This is also a great way to learn how to use React context, if you feel like you have time.
(passing state down is fine though, I would focus on finishing features over learning new syntax)

**Comment by aissshah** [comment]
done :)
