### ISSUE TITLE
Put onAuthStateChanged() call in a useEffect!

### ISSUE THREAD

**Issue by rooberrydev** [fac20/tfb-bonf#25]
Currently you're running the function directly inside the component body,

Doing stuff in the function body is dangerous (you have no control over when/how many times it runs)

Currently every time your app component reloads (page navigation for example) React is setting up a new onAuthStateChanged listener, and you'll end up with lots of listeners doing the same thing.

Putting it inside useEffect with an empty dependency array makes sure it only runs once.

The return value from onAuthStateChanged is handy too, it lets react remove the listener when the app unmounts.

The function returned from useEffect is used for clean up, so we can run unsubscribe () inside it to tell firebase to stop listening for auth changes.

```javascript
useEffect(() => {
    const unsubscribe = auth().onAuthStateChanged((user) => {
      if (user) {
        setLoading(false);
        setLoggedIn(true);
      } else {
        setLoading(false);
        setLoggedIn(false);
      }
    });
    return () => unsubscribe();
  }, []);
```

_Originally posted by @reubengt in https://github.com/fac20/tfb-bonf/issues/18#issuecomment-716918985_

**Comment by aissshah** [comment]
done :)
